Fetch disaster and conflict data
idmc-labs/gidd-dashboard pull request #1
Opened 2021-05-08 12:19 UTC by AdityaKhatri

2021-06-15 03:35 UTC, tnagorra requested changes

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/NumberBlock/index.tsx
> +    abbreviate = true,
```suggestion
    hiddenIfNoValue = false,
    abbreviated = true,
```

2021-06-15 03:35 UTC, tnagorra commented on src/utils/common.ts
> +    return data;
Use ternary operator

2021-06-15 03:35 UTC, tnagorra commented on src/utils/common.ts
> +    const topData = [...sortedData];
```suggestion
    const sortedData = [...data].sort((a, b) => compareNumber(a.total, b.total, -1));

    const topData = sortedData;
```

2021-06-15 03:35 UTC, tnagorra commented on src/Root/App/index.tsx
> +    };
please memoize

2021-06-15 03:35 UTC, tnagorra commented on src/components/CurvedBar/index.tsx
> +function CustomBar(props: any) {
```suggestion
function CurvedBar(props: any) {
```

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/MapDashboard/index.tsx
> +        },
please memoize

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/MapDashboard/index.tsx
> +    }, [response?.results]);
why not map and then filter?

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/MapDashboard/index.tsx
> +        const finalSortedData = [...response.results].map((d) => ({
Why create a new array?

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/MapDashboard/index.tsx
> +                    || sorting.name === 'year'
Better to use Array.includes

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/MapDashboard/index.tsx
> +        const finalPaginatedData = [...finalSortedData];
Why make a copy?

2021-06-15 03:35 UTC, tnagorra commented on src/views/Gidd/Disaster/index.tsx
> +                    || sorting.name === 'hazard_sub_type'
Better to use array.includes method

2021-06-16 09:35 UTC, AdityaKhatri commented on src/views/Gidd/MapDashboard/index.tsx
> +    }, [response?.results]);
We can do that, but we also need the length of how many exist. I find this a bit easier.

2021-06-16 09:41 UTC, AdityaKhatri commented on src/views/Gidd/MapDashboard/index.tsx
> +                    || sorting.name === 'year'
For some reason the typing inside the if condition didn't infer when i used Array.includes

2021-06-16 09:43 UTC, AdityaKhatri commented on src/views/Gidd/MapDashboard/index.tsx
> +        const finalPaginatedData = [...finalSortedData];
The paginatedData and sortedData both are exposed outside, if i didn't make a copy, the array would be mutated when I perform splice and trim.

2021-06-16 09:47 UTC, AdityaKhatri commented on src/views/Gidd/Disaster/index.tsx
> +                    || sorting.name === 'hazard_sub_type'
For some reason the typing inside the if the condition didn't infer when I used Array.includes

2021-06-19 11:09 UTC, tnagorra requested changes

2021-06-19 11:09 UTC, tnagorra commented on src/Root/index.tsx
> +import 'requestidlecallback-polyfill';
Was this added to package.json sideEffects ?

2022-04-26 06:07 UTC, AdityaKhatri commented on src/Root/index.tsx
> +import 'requestidlecallback-polyfill';
Yes

2022-04-26 06:07 UTC, AdityaKhatri commented on src/Root/index.tsx
> +import 'requestidlecallback-polyfill';
No

2022-04-26 06:11 UTC, tnagorra approved these changes

2022-04-26 06:17 UTC, merged